### ISSUE TITLE
Can not found the compiled Precise RoI Pooling library. Run ./travis.sh in the directory first.

### ISSUE THREAD

**Issue by Mr-doraemon** [CASIA-IVA-Lab/DCFST#2]
when I run the command that: _python run_tracker.py sbdt OTB2015 --dataset 'otb'_. The followling error will occur:_Can not found the compiled Precise RoI Pooling library. Run ./travis.sh in the directory first._ But I have complied the travis.sh file.
How should I solve this problem? Thank you

**Comment by noneUmbrella** [comment]
Our framework is based on pytracking. This question is introduced in more detail in pytracking, and there are many answers. We strongly recommend you to refer to the project of pytracking along with its issues.@Mr-doraemon
